{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "STATISTICS ANALYTICS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Users",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "SELECT COUNT(*) FROM logs.users"
      }
     ]
    },
    {
     "title": "Total Products",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "SELECT COUNT(*) FROM logs.products"
      }
     ]
    },
    {
     "title": "Fashion Products ",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 8, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "SELECT COUNT(*) FROM logs.products WHERE category = 'Fashion' ALLOW FILTERING"
      }
     ]
    },
    {
     "title": "Electronics Products",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 14, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "SELECT COUNT(*) FROM logs.products WHERE category = 'Electronics' ALLOW FILTERING"
      }
     ]
    },
    {
     "title": "Beauty Products",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 19, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "SELECT COUNT(*) FROM logs.products WHERE category = 'Beauty' ALLOW FILTERING"
      }
     ]
    },
    {
     "title": "Products by Category",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 10, "x": 0, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "SELECT category, product_count FROM logs.product_category_summary"
      }
     ]
    },
    {
     "title": " Average Price by Category",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 14, "x": 10, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "SELECT category, avg_price FROM logs.product_category_summary"
      }
     ]
    },
    {
     "title": "Users by City",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
     "targets": [
      {
       "target": "SELECT country, city, user_count, avg_age FROM logs.user_city_summary WHERE country = 'Egypt'"
      }
     ]
    }
   ]
  },
  {
   "title": "EVENT MONITORING",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Events",
     "type": "stat",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "SELECT COUNT(*) FROM logs.ecomm_log"
      }
     ]
    },
    {
     "title": "Purchase Events",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 6, "x": 5, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "SELECT COUNT(*) FROM logs.ecomm_log WHERE event_type = 'purchase' ALLOW FILTERING"
      }
     ]
    },
    {
     "title": "ERROR ALERT MONITOR",
     "type": "stat",
     "gridPos": { "h": 6, "w": 5, "x": 11, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "SELECT COUNT(*) FROM logs.ecomm_log WHERE level = 'ERROR' ALLOW FILTERING"
      }
     ]
    },
    {
     "title": "ACTIVITY HEATMAP",
     "type": "stat",
     "gridPos": { "h": 6, "w": 5, "x": 16, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "SELECT COUNT(*) as recent_activity \nFROM logs.ecomm_log \nWHERE timestamp > '2024-12-20T12:00:00Z' \nALLOW FILTERING"
      }
     ]
    },
    {
     "title": " Today's Events",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 21, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "SELECT COUNT(*) FROM logs.ecomm_log WHERE timestamp > '2025-07-15' ALLOW FILTERING"
      }
     ]
    },
    {
     "title": " LIVE EVENT STREAM",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "target": "SELECT timestamp, event_type, user_id, geo_city, details_amount \nFROM logs.ecomm_log \n"
      }
     ]
    }
   ]
  }
 ]
}